// src/userData.js
export const userList = [
  {
    id: 1,
    name: "Leanne Graham",
    email: "Sincere@april.biz",
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    avatar: "https://via.placeholder.com/150/f66b97/FFFFFF?text=LG",
    isLiked: false,
  },
  {
    id: 2,
    name: "Ervin Howell",
    email: "Shanna@melissa.tv",
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    avatar: "https://via.placeholder.com/150/771796/FFFFFF?text=EH",
    isLiked: false,
  },
  {
    id: 3,
    name: "Clementine Bauch",
    email: "Nathan@yesenia.net",
    phone: "1-463-123-4447",
    website: "ramiro.info",
    avatar: "https://via.placeholder.com/150/24f355/FFFFFF?text=CB",
    isLiked: false,
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    email: "Julianne.OConner@kory.org",
    phone: "493-170-9623 x156",
    website: "kale.biz",
    avatar: "https://via.placeholder.com/150/d32776/FFFFFF?text=PL",
    isLiked: false,
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    email: "Lucio_Hettinger@annie.ca",
    phone: "(254)954-1289",
    website: "demarco.info",
    avatar: "https://via.placeholder.com/150/92c952/FFFFFF?text=CD",
    isLiked: false,
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    email: "Karley_Dach@jasper.info",
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
    avatar: "https://via.placeholder.com/150/1ee22f/FFFFFF?text=DS",
    isLiked: false,
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    email: "Telly.Hoeger@billy.biz",
    phone: "210.067.6132",
    website: "elvis.io",
    avatar: "https://via.placeholder.com/150/ee7711/FFFFFF?text=KW",
    isLiked: false,
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    email: "Sherwood@rosamond.me",
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
    avatar: "https://via.placeholder.com/150/44bbff/FFFFFF?text=NR",
    isLiked: false,
  },
  {
    id: 9,
    name: "Glenna Reichert",
    email: "Chaim_McDermott@dana.io",
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
    avatar: "https://via.placeholder.com/150/aaaa11/FFFFFF?text=GR",
    isLiked: false,
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    email: "Rey.Padberg@karina.biz",
    phone: "024-648-3804",
    website: "ambrose.net",
    avatar: "https://via.placeholder.com/150/ff4444/FFFFFF?text=CD",
    isLiked: false,
  },
];